name: CI
on: [pull_request, push]
jobs:
  Awesome_Lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: npm ci
      - run: npm test
